language: java
script: mvn -P with-sources-and-javadocs -Ddeploy=snapshot -DskipTests=true -s .travis.settings.xml
env: 
  global: 
  - secure: AjeWt1KvcfpTqHW2/5UVsfVc/S9daNM6g099Bum+BxaILlNvsgQvjT+BTfQK96AdLXrJ6irRHdSfO6XR9WQxG18uz932pkZCAqqIh+zPIeYD+OJ66hoCYlAAjWpkYUP/Jx8P3lvf7Tu+k1k+HfjbgC7G3YRT0uCIm+G0GjaD9BU=
  - secure: EiG4O9aoHH215TxrczX+a6G75l4RsAf6SMpekSuQLXgAT8UzcAKMASMKtpwmwx8FAvJ8uYEh8W0akyuO9V8xXFXXB2hccGloJuwQi+Du0/837P6oHDx7WMZo5NOepzwrvJCdtUBRgH8uuTMyG9UMMFqRqnVA0cV3antIId5Vj3k=
